### ISSUE TITLE
Icon not found

### ISSUE THREAD

**Issue by TechWatching** [twitwi/slidev-addon-remoji#1]
When following the instruction, I have the following error : 

`2:03:27 PM [vite] Internal server error: Icon `openmoji/personal-computer` not found`

It seems the emoticon is properly replaced by openmoji/personal-computer but that this icon is not found.

Is there another missing dependency to add?

**Comment by twitwi** [comment]
Sorry I missed the issue.

I'm using a list of emoji names but unfortunately not all provider follow this list... and that's why I need a fixing code
https://github.com/twitwi/slidev-addon-remoji/blob/main/setup/preparser.ts#L3-L21

As most emojis are actually unavailable it is difficult to find the relevant fixes to apply.
I'll try to fix at least the ones from the demo...

**Comment by twitwi** [comment]
should be fixed by [#d0c9de1941269bd60d0c91569756cf118267fc4e](https://github.com/twitwi/slidev-addon-remoji/commit/d0c9de1941269bd60d0c91569756cf118267fc4e)
